"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarDays, CircleDollarSign, PackageSearch, ShoppingBag, UsersRound } from "lucide-react";
import type { T_Customer } from "@/entities/customer";
import type { T_Order } from "@/entities/order";
import type { T_ServicesState } from "@/entities/service";
import type { T_User } from "@/entities/user";
import type { T_WarehouseState } from "@/entities/warehouse";
import { getCustomers } from "@/shared/api/customers";
import { getOrders } from "@/shared/api/orders";
import { getServicesState } from "@/shared/api/services";
import { getUsers } from "@/shared/api/users";
import { getWarehouseState } from "@/shared/api/warehouse";
import { useI18n } from "@/shared/i18n";
import { Button, Select } from "@/shared/ui";
import { AdminCard, AdminPage } from "@/widgets/AdminWidgets";
import { calculateAnalytics, type T_AnalyticsPeriod } from "../../model/analytics";

type T_Data = { orders: T_Order[]; customers: T_Customer[]; users: T_User[]; warehouse: T_WarehouseState; services: T_ServicesState };
const emptyData: T_Data = { orders: [], customers: [], users: [], warehouse: { warehouses: [], inventoryItems: [], balances: [], movements: [] }, services: { categories: [], services: [], providers: [], locations: [], appointments: [] } };

export const AnalyticsDashboard = () => {
  const { t, locale } = useI18n(); const [data, setData] = useState<T_Data>(emptyData); const [period, setPeriod] = useState<T_AnalyticsPeriod>("30"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const readData = useCallback(() => Promise.all([getOrders(), getCustomers(), getUsers().catch(() => []), getWarehouseState(), getServicesState()]), []);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [orders, customers, users, warehouse, services] = await readData(); setData({ orders, customers, users, warehouse, services }); } catch { setError(t("admin.analytics.error")); } finally { setLoading(false); } }, [readData, t]);
  useEffect(() => { let active = true; readData().then(([orders, customers, users, warehouse, services]) => { if (active) setData({ orders, customers, users, warehouse, services }); }).catch(() => { if (active) setError(t("admin.analytics.error")); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [readData, t]);
  const analytics = useMemo(() => calculateAnalytics({ ...data, period }), [data, period]);
  const money = (value: number) => new Intl.NumberFormat(locale, { style: "currency", currency: analytics.currency, maximumFractionDigits: 0 }).format(value); const number = (value: number) => new Intl.NumberFormat(locale).format(value);
  const maxTrend = Math.max(...analytics.trend.map((item) => item.revenue), 1); const maxStatus = Math.max(...analytics.statusCounts.map((item) => item.count), 1);

  return <AdminPage title={t("admin.analytics.title")} description={t("admin.analytics.description")} actions={<div className="w-44"><Select aria-label={t("admin.analytics.period")} value={period} onChange={(event) => setPeriod(event.target.value as T_AnalyticsPeriod)} options={(["7", "30", "90", "all"] as const).map((value) => ({ value, label: t(`admin.analytics.period.${value}`) }))} /></div>}>
    {loading ? <AdminCard title={t("common.dataState.loading")}><div className="h-32 animate-pulse bg-surface-muted" /></AdminCard> : error ? <AdminCard title={t("common.dataState.error")}><p className="text-sm text-danger">{error}</p><Button className="mt-4 h-10" onClick={() => void load()}>{t("common.dataState.retry")}</Button></AdminCard> : <div className="space-y-5">
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={CircleDollarSign} label={t("admin.analytics.revenue")} value={money(analytics.revenue)} delta={analytics.revenueDelta} /><Metric icon={ShoppingBag} label={t("admin.analytics.orders")} value={number(analytics.orders)} delta={analytics.ordersDelta} /><Metric icon={UsersRound} label={t("admin.analytics.newCustomers")} value={number(analytics.customers)} detail={`${t("admin.analytics.total")}: ${number(analytics.totalCustomers)}`} /><Metric icon={CalendarDays} label={t("admin.analytics.appointments")} value={number(analytics.appointments)} detail={`${t("admin.analytics.completed")}: ${number(analytics.completedAppointments)}`} /><Metric icon={PackageSearch} label={t("admin.analytics.lowStock")} value={number(analytics.lowStock)} detail={`${t("admin.analytics.availableUnits")}: ${number(analytics.availableStock)}`} /></div>
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.7fr)_minmax(18rem,0.8fr)]"><AdminCard title={t("admin.analytics.revenueTrend")} description={t("admin.analytics.revenueTrendDescription")}><div className="flex h-64 items-end gap-1 border-b border-border pt-6" aria-label={t("admin.analytics.revenueTrend")}>{analytics.trend.map((item, index) => <div key={item.date} className="group relative flex min-w-0 flex-1 items-end" style={{ height: "100%" }}><div className="w-full bg-accent transition-opacity hover:opacity-75" style={{ height: `${Math.max(2, item.revenue / maxTrend * 100)}%` }} /><div className="pointer-events-none absolute bottom-full left-1/2 z-10 hidden -translate-x-1/2 whitespace-nowrap border border-border bg-background px-2 py-1 text-xs group-hover:block">{item.date}: {money(item.revenue)}</div>{(index === 0 || index === analytics.trend.length - 1) && <span className="absolute top-full mt-2 text-xs text-muted">{item.date.slice(5)}</span>}</div>)}</div></AdminCard><AdminCard title={t("admin.analytics.orderStatus")}><div className="space-y-4">{analytics.statusCounts.map((item) => <div key={item.status}><div className="mb-1 flex justify-between text-sm"><span>{t(`admin.orders.status.${item.status}`)}</span><strong>{item.count}</strong></div><div className="h-2 bg-surface-muted"><div className="h-full bg-accent" style={{ width: `${item.count / maxStatus * 100}%` }} /></div></div>)}</div></AdminCard></div>
      <div className="grid gap-5 xl:grid-cols-3"><AdminCard title={t("admin.analytics.commerce")}><dl className="grid grid-cols-2 gap-4"><Stat label={t("admin.analytics.averageOrder")} value={money(analytics.averageOrder)} /><Stat label={t("admin.analytics.activeOrders")} value={number(analytics.activeOrders)} /></dl></AdminCard><AdminCard title={t("admin.analytics.services")}><dl className="grid grid-cols-2 gap-4"><Stat label={t("admin.analytics.appointments")} value={number(analytics.appointments)} /><Stat label={t("admin.analytics.completed")} value={number(analytics.completedAppointments)} /></dl></AdminCard><AdminCard title={t("admin.analytics.warehouse")}><dl className="grid grid-cols-2 gap-4"><Stat label={t("admin.analytics.lowStock")} value={number(analytics.lowStock)} /><Stat label={t("admin.analytics.availableUnits")} value={number(analytics.availableStock)} /></dl></AdminCard></div>
      <div className="grid gap-5 xl:grid-cols-2"><AdminCard title={t("admin.analytics.topProducts")}><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-border text-muted"><tr><th className="p-3">{t("admin.analytics.product")}</th><th className="p-3">{t("admin.analytics.quantity")}</th><th className="p-3">{t("admin.analytics.revenue")}</th></tr></thead><tbody>{analytics.topProducts.map((item) => <tr key={item.title} className="border-b border-border last:border-0"><td className="p-3 font-medium">{item.title}</td><td className="p-3">{item.quantity}</td><td className="p-3">{money(item.revenue)}</td></tr>)}</tbody></table>{!analytics.topProducts.length && <p className="p-4 text-sm text-muted">{t("admin.analytics.noSales")}</p>}</div></AdminCard><AdminCard title={t("admin.analytics.staffPerformance")} description={t("admin.analytics.staffPerformanceDescription")}><div className="space-y-3">{analytics.staff.map((item) => <div key={item.id} className="flex items-center justify-between border-b border-border pb-3 last:border-0"><div><p className="font-medium">{item.name}</p><p className="text-xs text-muted">{t(`admin.auth.role.${item.role}`)}</p></div><strong>{item.actions}</strong></div>)}{!analytics.staff.length && <p className="text-sm text-muted">{t("admin.analytics.noStaff")}</p>}</div></AdminCard></div>
    </div>}
  </AdminPage>;
};

const Metric = ({ icon: Icon, label, value, delta, detail }: { icon: typeof CircleDollarSign; label: string; value: string; delta?: number; detail?: string }) => <AdminCard title={label}><div className="flex items-start justify-between gap-3"><div><p className="text-2xl font-semibold">{value}</p>{delta !== undefined && <p className={`mt-1 text-xs ${delta >= 0 ? "text-success" : "text-danger"}`}>{delta >= 0 ? "+" : ""}{delta.toFixed(1)}%</p>}{detail && <p className="mt-1 text-xs text-muted">{detail}</p>}</div><Icon className="h-5 w-5 text-accent" /></div></AdminCard>;
const Stat = ({ label, value }: { label: string; value: string }) => <div><dt className="text-sm text-muted">{label}</dt><dd className="mt-1 text-xl font-semibold">{value}</dd></div>;
