"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { T_AppointmentStatus, T_ServicesState, T_WeeklySchedule } from "@/entities/service";
import { useAdminAccess } from "@/features/auth";
import { getServicesState, saveServiceCategory, saveServiceLocation, saveServiceProvider, ServicesApiError, updateAppointment } from "@/shared/api/services";
import { useI18n } from "@/shared/i18n";
import { Button, Input, Select, Textarea } from "@/shared/ui";
import { AdminCard, AdminFormAlert, AdminPage } from "@/widgets/AdminWidgets";

type T_Tab = "catalog" | "providers" | "locations" | "appointments";
const emptyState: T_ServicesState = { categories: [], services: [], providers: [], locations: [], appointments: [] };
const defaultSchedule = (): T_WeeklySchedule[] => Array.from({ length: 7 }, (_, dayOfWeek) => ({ dayOfWeek, enabled: dayOfWeek > 0 && dayOfWeek < 6, periods: [{ start: "09:00", end: "18:00" }], breaks: [{ start: "13:00", end: "14:00" }] }));
const statusKeys: Record<T_AppointmentStatus, "admin.services.status.pending" | "admin.services.status.confirmed" | "admin.services.status.completed" | "admin.services.status.cancelled" | "admin.services.status.no_show"> = { pending: "admin.services.status.pending", confirmed: "admin.services.status.confirmed", completed: "admin.services.status.completed", cancelled: "admin.services.status.cancelled", no_show: "admin.services.status.no_show" };

export const ServicesManagement = () => {
  const { t } = useI18n(); const { canManage, session } = useAdminAccess();
  const [tab, setTab] = useState<T_Tab>("catalog"); const [state, setState] = useState<T_ServicesState>(emptyState);
  const [categoryForm, setCategoryForm] = useState({ name: "", slug: "" }); const [providerForm, setProviderForm] = useState({ name: "", email: "", phone: "", bio: "" });
  const [locationForm, setLocationForm] = useState({ name: "", address: "", timezone: "Europe/Berlin", capacity: "1" });
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [isLoading, setIsLoading] = useState(true);
  const reload = useCallback(async () => setState(await getServicesState()), []);
  useEffect(() => { getServicesState().then(setState).catch(() => setError(t("admin.services.error.load"))).finally(() => setIsLoading(false)); }, [t]);
  const run = async (action: () => Promise<unknown>, success: string) => { setError(""); setMessage(""); try { await action(); await reload(); setMessage(success); return true; } catch (caught) { setError(caught instanceof ServicesApiError ? caught.message : t("admin.services.error.save")); return false; } };
  const tabs: Array<{ id: T_Tab; label: string; count: number }> = [
    { id: "catalog", label: t("admin.services.tabs.catalog"), count: state.services.length }, { id: "providers", label: t("admin.services.tabs.providers"), count: state.providers.length },
    { id: "locations", label: t("admin.services.tabs.locations"), count: state.locations.length }, { id: "appointments", label: t("admin.services.tabs.appointments"), count: state.appointments.length },
  ];
  const serviceMap = useMemo(() => new Map(state.services.map((item) => [item.id, item])), [state.services]);
  if (isLoading) return <AdminPage title={t("admin.services.title")}><p className="text-muted">{t("common.dataState.loading")}</p></AdminPage>;

  return <AdminPage title={t("admin.services.title")} description={t("admin.services.description")}><div className="space-y-5">
    <div className="flex gap-1 overflow-x-auto border-b border-border" role="tablist">{tabs.map((item) => <button key={item.id} type="button" role="tab" aria-selected={tab === item.id} className={`min-h-11 shrink-0 border-b-2 px-4 text-sm font-medium ${tab === item.id ? "border-accent text-accent" : "border-transparent text-muted hover:text-foreground"}`} onClick={() => setTab(item.id)}>{item.label} <span className="ml-1 text-xs">{item.count}</span></button>)}</div>
    <AdminFormAlert message={error} />{message && <p role="status" className="rounded-md border border-accent bg-accent/10 p-3 text-sm">{message}</p>}

    {tab === "catalog" && <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_20rem]"><AdminCard title={t("admin.services.catalogTitle")}><div className="space-y-3">{state.services.length ? state.services.map((service) => <article key={service.id} className="grid gap-3 border-b border-border pb-3 last:border-0 sm:grid-cols-[1fr_auto] sm:items-center"><div><Link href={`/admin/services/${service.id}/edit`} className="font-semibold hover:text-accent hover:underline">{service.title}</Link><p className="text-sm text-muted">{service.durationMinutes} min · {service.priceType === "from" ? `${t("admin.services.from")} ` : ""}{service.price} {service.currency} · {service.variants.length} / {service.addOns.length}</p></div><span className="text-sm text-muted">{service.status}</span></article>) : <p className="text-sm text-muted">{t("admin.services.empty.services")}</p>}</div></AdminCard>{canManage && <div className="space-y-5"><Link className="flex h-10 items-center justify-center rounded-md bg-accent px-4 font-medium text-background" href="/admin/services/new">{t("admin.services.actions.createService")}</Link><AdminCard title={t("admin.services.createCategory")}><form className="grid gap-3" onSubmit={async (event) => { event.preventDefault(); if (await run(() => saveServiceCategory({ ...categoryForm, status: "active" }), t("admin.services.success.category"))) setCategoryForm({ name: "", slug: "" }); }}><Input required label={t("admin.services.fields.name")} value={categoryForm.name} onChange={(event) => setCategoryForm({ ...categoryForm, name: event.target.value })} /><Input required label="Slug" value={categoryForm.slug} onChange={(event) => setCategoryForm({ ...categoryForm, slug: event.target.value })} /><Button type="submit" className="h-10">{t("admin.services.actions.createCategory")}</Button></form></AdminCard></div>}</div>}

    {tab === "providers" && <div className="grid gap-5 xl:grid-cols-[1fr_24rem]"><AdminCard title={t("admin.services.providersTitle")}><div className="space-y-3">{state.providers.map((provider) => <div key={provider.id} className="flex items-center justify-between gap-3 border-b border-border pb-3 last:border-0"><div><p className="font-semibold">{provider.name}</p><p className="text-sm text-muted">{provider.email} · {provider.phone}</p></div><Link className="text-sm text-accent hover:underline" href={`/admin/services/schedules/provider/${provider.id}`}>{t("admin.services.schedule.action")}</Link></div>)}</div></AdminCard>{canManage && <AdminCard title={t("admin.services.createProvider")}><form className="grid gap-3" onSubmit={async (event) => { event.preventDefault(); if (await run(() => saveServiceProvider({ ...providerForm, imageUrl: "", serviceIds: state.services.map((item) => item.id), locationIds: state.locations.map((item) => item.id), schedule: defaultSchedule(), blockedSlots: [], status: "active" }), t("admin.services.success.provider"))) setProviderForm({ name: "", email: "", phone: "", bio: "" }); }}><Input required label={t("admin.services.fields.name")} value={providerForm.name} onChange={(event) => setProviderForm({ ...providerForm, name: event.target.value })} /><Input type="email" label={t("admin.services.fields.email")} value={providerForm.email} onChange={(event) => setProviderForm({ ...providerForm, email: event.target.value })} /><Input label={t("admin.services.fields.phone")} value={providerForm.phone} onChange={(event) => setProviderForm({ ...providerForm, phone: event.target.value })} /><Textarea label={t("admin.services.fields.bio")} value={providerForm.bio} onChange={(event) => setProviderForm({ ...providerForm, bio: event.target.value })} /><Button type="submit" className="h-10">{t("admin.services.actions.createProvider")}</Button></form></AdminCard>}</div>}
    {tab === "locations" && <div className="grid gap-5 xl:grid-cols-[1fr_24rem]"><AdminCard title={t("admin.services.locationsTitle")}><div className="space-y-3">{state.locations.map((location) => <div key={location.id} className="flex items-center justify-between gap-3 border-b border-border pb-3 last:border-0"><div><p className="font-semibold">{location.name}</p><p className="text-sm text-muted">{location.address} · {location.timezone}</p></div><Link className="text-sm text-accent hover:underline" href={`/admin/services/schedules/location/${location.id}`}>{t("admin.services.schedule.action")}</Link></div>)}</div></AdminCard>{canManage && <AdminCard title={t("admin.services.createLocation")}><form className="grid gap-3" onSubmit={async (event) => { event.preventDefault(); if (await run(() => saveServiceLocation({ ...locationForm, capacity: Number(locationForm.capacity), schedule: defaultSchedule(), blockedSlots: [], status: "active" }), t("admin.services.success.location"))) setLocationForm({ name: "", address: "", timezone: "Europe/Berlin", capacity: "1" }); }}><Input required label={t("admin.services.fields.name")} value={locationForm.name} onChange={(event) => setLocationForm({ ...locationForm, name: event.target.value })} /><Input label={t("admin.services.fields.address")} value={locationForm.address} onChange={(event) => setLocationForm({ ...locationForm, address: event.target.value })} /><Input required label={t("admin.services.fields.timezone")} value={locationForm.timezone} onChange={(event) => setLocationForm({ ...locationForm, timezone: event.target.value })} /><Input required type="number" min="1" label={t("admin.services.fields.capacity")} value={locationForm.capacity} onChange={(event) => setLocationForm({ ...locationForm, capacity: event.target.value })} /><Button type="submit" className="h-10">{t("admin.services.actions.createLocation")}</Button></form></AdminCard>}</div>}
    {tab === "appointments" && <AdminCard title={t("admin.services.appointmentsTitle")}><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-border text-muted"><tr><th className="p-3">{t("admin.services.fields.customer")}</th><th className="p-3">{t("admin.services.fields.service")}</th><th className="p-3">{t("admin.services.fields.date")}</th><th className="p-3">{t("admin.services.fields.status")}</th></tr></thead><tbody>{state.appointments.map((appointment) => <tr key={appointment.id} className="border-b border-border"><td className="p-3"><Link className="font-semibold hover:text-accent hover:underline" href={`/admin/services/appointments/${appointment.id}`}>{appointment.customerName}</Link><span className="block text-xs text-muted">{appointment.customerEmail}</span></td><td className="p-3">{serviceMap.get(appointment.serviceId)?.title ?? appointment.serviceId}</td><td className="p-3">{new Date(appointment.startAt).toLocaleString()}</td><td className="p-3"><Select aria-label={t("admin.services.fields.status")} disabled={!canManage} value={appointment.status} onChange={(event) => void run(() => updateAppointment({ id: appointment.id, status: event.target.value as T_AppointmentStatus, cancellationReason: event.target.value === "cancelled" ? t("admin.services.appointment.quickCancelReason") : undefined, updatedBy: session?.displayName ?? "Staff" }), t("admin.services.success.appointment"))} options={(Object.keys(statusKeys) as T_AppointmentStatus[]).map((value) => ({ value, label: t(statusKeys[value]) }))} /></td></tr>)}</tbody></table>{!state.appointments.length && <p className="p-4 text-sm text-muted">{t("admin.services.empty.appointments")}</p>}</div></AdminCard>}
  </div></AdminPage>;
};
